### ISSUE TITLE
Portfolio-page-review

### ISSUE THREAD

**Issue by Sahar-AbdelSamad** [mukhammadrizooff/Portfolio-Page-#4]
# Hi @mukhammadrizooff  👋🏻 

You've done a great job so far :clap: :clap: :clap: 

## To highlight 👍🏻  ##  
:heavy_check_mark: The use of the units is very smart
:heavy_check_mark: The app is responsive

## Suggestions :stars: ##
- [ ]  We suggest that you use font awesome or google icons for your social icons instead of images

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

Cheers and Happy coding! 🎉🎉🎉

**Comment by mukhammadrizooff** [comment]
Thank you for your advice.
